// Map of "entity/flow" -> lazy loader for the flow component. A flow is "live"
// once it has an entry here; unlisted flows render the scheduled placeholder.
// Each entry is a dynamic import so Next code-splits one chunk per flow.
export const FLOW_LOADERS = {
  "amazon/add-to-cart-variant": () => import("@/app/entity-flows/amazon/add-to-cart-variant.js"),
  "amazon/order-tracking": () => import("@/app/entity-flows/amazon/order-tracking.js"),
  "chase/login-2fa": () => import("@/app/entity-flows/chase/login-2fa.js"),
  "lemonade/instant-quote": () => import("@/app/entity-flows/lemonade/instant-quote.js"),
  "slack/thread-reply": () => import("@/app/entity-flows/slack/thread-reply.js"),
  "airtable/grid-crud": () => import("@/app/entity-flows/airtable/grid-crud.js"),
  "calendly/invitee-booking": () => import("@/app/entity-flows/calendly/invitee-booking.js"),
  "netflix/playback-resume": () => import("@/app/entity-flows/netflix/playback-resume.js"),
  "amazon/one-click-checkout": () => import("@/app/entity-flows/amazon/one-click-checkout.js"),
  "shopify/guest-checkout": () => import("@/app/entity-flows/shopify/guest-checkout.js"),
  "shopify/discount-code": () => import("@/app/entity-flows/shopify/discount-code.js"),
  "shopify/checkout-extension": () => import("@/app/entity-flows/shopify/checkout-extension.js"),
  "flipkart/cart-exchange-offer": () => import("@/app/entity-flows/flipkart/cart-exchange-offer.js"),
  "flipkart/cod-checkout": () => import("@/app/entity-flows/flipkart/cod-checkout.js"),
  "walmart/store-pickup": () => import("@/app/entity-flows/walmart/store-pickup.js"),
  "walmart/grocery-substitution": () => import("@/app/entity-flows/walmart/grocery-substitution.js"),
  "walmart/membership-upsell": () => import("@/app/entity-flows/walmart/membership-upsell.js"),
  "walmart/reorder-from-history": () => import("@/app/entity-flows/walmart/reorder-from-history.js"),
  "etsy/personalized-item": () => import("@/app/entity-flows/etsy/personalized-item.js"),
  "etsy/multi-seller-cart": () => import("@/app/entity-flows/etsy/multi-seller-cart.js"),
  "ebay/buy-it-now": () => import("@/app/entity-flows/ebay/buy-it-now.js"),
  "instacart/multi-store-cart": () => import("@/app/entity-flows/instacart/multi-store-cart.js"),
  "instacart/delivery-slot-checkout": () => import("@/app/entity-flows/instacart/delivery-slot-checkout.js"),
  "instacart/tip-adjustment": () => import("@/app/entity-flows/instacart/tip-adjustment.js"),
  "nike/checkout-saved-card": () => import("@/app/entity-flows/nike/checkout-saved-card.js"),
  "stripe/hosted-checkout": () => import("@/app/entity-flows/stripe/hosted-checkout.js"),
  "stripe/3ds-challenge": () => import("@/app/entity-flows/stripe/3ds-challenge.js"),
  "stripe/declined-card-recovery": () => import("@/app/entity-flows/stripe/declined-card-recovery.js"),
  "paypal/express-checkout": () => import("@/app/entity-flows/paypal/express-checkout.js"),
  "paypal/guest-card-payment": () => import("@/app/entity-flows/paypal/guest-card-payment.js"),
  "razorpay/checkout-modal": () => import("@/app/entity-flows/razorpay/checkout-modal.js"),
  "razorpay/upi-intent": () => import("@/app/entity-flows/razorpay/upi-intent.js"),
  "razorpay/emi-options": () => import("@/app/entity-flows/razorpay/emi-options.js"),
  "razorpay/payment-link": () => import("@/app/entity-flows/razorpay/payment-link.js"),
  "square/checkout-link": () => import("@/app/entity-flows/square/checkout-link.js"),
  "square/invoice-pay": () => import("@/app/entity-flows/square/invoice-pay.js"),
  "square/tip-and-receipt": () => import("@/app/entity-flows/square/tip-and-receipt.js"),
  "adyen/drop-in-payment": () => import("@/app/entity-flows/adyen/drop-in-payment.js"),
  "adyen/ideal-redirect": () => import("@/app/entity-flows/adyen/ideal-redirect.js"),
  "adyen/stored-card-reuse": () => import("@/app/entity-flows/adyen/stored-card-reuse.js"),
  "klarna/pay-in-4": () => import("@/app/entity-flows/klarna/pay-in-4.js"),
  "klarna/credit-decline-fallback": () => import("@/app/entity-flows/klarna/credit-decline-fallback.js"),
  "wise/transfer-quote": () => import("@/app/entity-flows/wise/transfer-quote.js"),
  "wise/add-recipient": () => import("@/app/entity-flows/wise/add-recipient.js"),
  "wise/transfer-tracking": () => import("@/app/entity-flows/wise/transfer-tracking.js"),
  "wise/balance-conversion": () => import("@/app/entity-flows/wise/balance-conversion.js"),
  "revolut/card-freeze": () => import("@/app/entity-flows/revolut/card-freeze.js"),
  "chase/zelle-transfer": () => import("@/app/entity-flows/chase/zelle-transfer.js"),
  "chase/bill-pay-scheduling": () => import("@/app/entity-flows/chase/bill-pay-scheduling.js"),
  "chase/statement-download": () => import("@/app/entity-flows/chase/statement-download.js"),
  "chase/card-dispute": () => import("@/app/entity-flows/chase/card-dispute.js"),
  "hdfc-bank/netbanking-login": () => import("@/app/entity-flows/hdfc-bank/netbanking-login.js"),
  "hdfc-bank/imps-transfer": () => import("@/app/entity-flows/hdfc-bank/imps-transfer.js"),
  "hdfc-bank/fd-creation": () => import("@/app/entity-flows/hdfc-bank/fd-creation.js"),
  "hdfc-bank/card-statement": () => import("@/app/entity-flows/hdfc-bank/card-statement.js"),
  "american-express/rewards-redemption": () => import("@/app/entity-flows/american-express/rewards-redemption.js"),
  "american-express/payment-scheduling": () => import("@/app/entity-flows/american-express/payment-scheduling.js"),
  "american-express/dispute-charge": () => import("@/app/entity-flows/american-express/dispute-charge.js"),
  "american-express/offers-enrollment": () => import("@/app/entity-flows/american-express/offers-enrollment.js"),
};

export const LIVE_FLOW_KEYS = Object.keys(FLOW_LOADERS);
export function hasFlow(key) {
  return Object.prototype.hasOwnProperty.call(FLOW_LOADERS, key);
}
