// Entity Evals registry: 50 entities / 209 flows (every catalog row with Owner = Bhawana, rows 2-210).
// Merges the raw catalog (lib/catalog.js) with routing, skin, pattern-engine and
// schedule metadata. Drives the homepage "Entity Evals" section, the
// /{entity}/{flow} routes, entity landing pages and test.md generation.
import { CATALOG } from "./catalog.js";

export const SITE_URL = "https://my-testing-repo-main.vercel.app";

/**
 * @typedef {"checkout"|"auth"|"wizard"|"crud"|"tracker"|"media"|"booking"|"feed"|"custom"} Pattern
 * @typedef {{no:number, slug:string, name:string, skin:string, industry:string, icon:string,
 *   accent:string, accent2:string, mode:"light"|"dark", tagline:string}} Entity
 * @typedef {import("./catalog").CatalogRow & {
 *   entitySlug:string, skin:string, slug:string, path:string, url:string, testPath:string,
 *   pattern:Pattern, day:number, skinObjective:string, skinAssertion:string, mobile:boolean }} Flow
 */

export const PATTERN_LABELS = {
  checkout: "Checkout engine",
  auth: "Auth engine",
  wizard: "Form wizard",
  crud: "CRUD table / board",
  tracker: "Tracker timeline",
  media: "Media player",
  booking: "Booking calendar",
  feed: "Feed / messaging",
  custom: "Custom",
};

/** @type {Entity[]} */
export const ENTITIES = [
  { no: 1, slug: "amazon", name: "Amazon", skin: "Amazonia", industry: "E-commerce", icon: "📦", accent: "#f59e0b", accent2: "#131921", mode: "light", tagline: "Everything store" },
  { no: 2, slug: "shopify", name: "Shopify", skin: "Shopifly", industry: "E-commerce", icon: "🛍️", accent: "#5c6ac4", accent2: "#0f172a", mode: "light", tagline: "Storefront + admin" },
  { no: 3, slug: "flipkart", name: "Flipkart", skin: "Flipmart", industry: "E-commerce", icon: "🛒", accent: "#2874f0", accent2: "#fb641b", mode: "light", tagline: "India's marketplace" },
  { no: 4, slug: "walmart", name: "Walmart", skin: "Walmartly", industry: "E-commerce", icon: "🏬", accent: "#0071dc", accent2: "#ffc220", mode: "light", tagline: "Save money. Live better." },
  { no: 5, slug: "etsy", name: "Etsy", skin: "Etsily", industry: "E-commerce", icon: "🧶", accent: "#f1641e", accent2: "#222222", mode: "light", tagline: "Handmade marketplace" },
  { no: 6, slug: "ebay", name: "eBay", skin: "eBidz", industry: "E-commerce", icon: "🔨", accent: "#e53238", accent2: "#0064d2", mode: "light", tagline: "Auctions and Buy It Now" },
  { no: 7, slug: "instacart", name: "Instacart", skin: "Instakart", industry: "E-commerce", icon: "🥕", accent: "#0aad0a", accent2: "#003d29", mode: "light", tagline: "Grocery delivery" },
  { no: 8, slug: "nike", name: "Nike", skin: "Nyke", industry: "E-commerce", icon: "👟", accent: "#111111", accent2: "#fa5400", mode: "light", tagline: "Just move." },
  { no: 9, slug: "stripe", name: "Stripe", skin: "Stripely", industry: "Payments infra", icon: "💳", accent: "#635bff", accent2: "#0a2540", mode: "light", tagline: "Payments infrastructure" },
  { no: 10, slug: "paypal", name: "PayPal", skin: "PayPally", industry: "Payments infra", icon: "🅿️", accent: "#003087", accent2: "#0070ba", mode: "light", tagline: "Send, receive, pay" },
  { no: 11, slug: "razorpay", name: "Razorpay", skin: "Razorpaid", industry: "Payments infra", icon: "⚡", accent: "#3395ff", accent2: "#0b2447", mode: "light", tagline: "Indian payment gateway" },
  { no: 12, slug: "square", name: "Square", skin: "Squarely", industry: "Payments infra", icon: "◼️", accent: "#006aff", accent2: "#1a1a1a", mode: "light", tagline: "POS, invoices, checkout" },
  { no: 13, slug: "adyen", name: "Adyen", skin: "Adyenly", industry: "Payments infra", icon: "🟢", accent: "#0abf53", accent2: "#00112c", mode: "light", tagline: "Global payments platform" },
  { no: 14, slug: "klarna", name: "Klarna", skin: "Klarnah", industry: "Payments infra", icon: "🩷", accent: "#ffb3c7", accent2: "#17120f", mode: "light", tagline: "Pay in 4" },
  { no: 15, slug: "wise", name: "Wise", skin: "Wyse", industry: "Payments infra", icon: "🌍", accent: "#9fe870", accent2: "#163300", mode: "light", tagline: "International money transfer" },
  { no: 16, slug: "robinhood", name: "Robinhood", skin: "Robinhoot", industry: "Consumer fintech", icon: "🪶", accent: "#00c805", accent2: "#1b1b1d", mode: "dark", tagline: "Commission-free investing" },
  { no: 17, slug: "zerodha", name: "Zerodha", skin: "Zerodhi", industry: "Consumer fintech", icon: "📈", accent: "#387ed1", accent2: "#ff5722", mode: "light", tagline: "Kite-style trading terminal" },
  { no: 18, slug: "coinbase", name: "Coinbase", skin: "Coinbayse", industry: "Consumer fintech", icon: "🪙", accent: "#0052ff", accent2: "#0a0b0d", mode: "light", tagline: "Crypto exchange" },
  { no: 19, slug: "revolut", name: "Revolut", skin: "Revolute", industry: "Consumer fintech", icon: "💠", accent: "#191c1f", accent2: "#4f55f1", mode: "dark", tagline: "All-in-one money app" },
  { no: 20, slug: "paytm", name: "Paytm", skin: "Paytum", industry: "Consumer fintech", icon: "📱", accent: "#002e6e", accent2: "#00b9f1", mode: "light", tagline: "UPI wallet super-app" },
  { no: 21, slug: "phonepe", name: "PhonePe", skin: "PhonePay", industry: "Consumer fintech", icon: "💜", accent: "#5f259f", accent2: "#ffffff", mode: "light", tagline: "UPI payments app" },
  { no: 22, slug: "venmo", name: "Venmo", skin: "Venmoo", industry: "Consumer fintech", icon: "💸", accent: "#008cff", accent2: "#0074de", mode: "light", tagline: "Social payments" },
  { no: 23, slug: "chase", name: "Chase", skin: "Chaise Bank", industry: "Banking", icon: "🏦", accent: "#117aca", accent2: "#0b2e4f", mode: "light", tagline: "Retail bank portal" },
  { no: 24, slug: "hdfc-bank", name: "HDFC Bank", skin: "HDFB Bank", industry: "Banking", icon: "🏛️", accent: "#004c8f", accent2: "#ed232a", mode: "light", tagline: "NetBanking portal" },
  { no: 25, slug: "american-express", name: "American Express", skin: "Amerix", industry: "Banking", icon: "💎", accent: "#006fcf", accent2: "#0b1f3a", mode: "light", tagline: "Premium card membership" },
  { no: 26, slug: "lemonade", name: "Lemonade", skin: "Lemonaid", industry: "Insurance", icon: "🍋", accent: "#ff0083", accent2: "#111111", mode: "light", tagline: "Chat-first insurance" },
  { no: 27, slug: "policybazaar", name: "Policybazaar", skin: "PolicyMart", industry: "Insurance", icon: "🛡️", accent: "#0065ff", accent2: "#f7b500", mode: "light", tagline: "Insurance comparison" },
  { no: 28, slug: "salesforce", name: "Salesforce", skin: "Salesforze", industry: "CRM", icon: "☁️", accent: "#0176d3", accent2: "#032d60", mode: "light", tagline: "Lightning CRM" },
  { no: 29, slug: "hubspot", name: "HubSpot", skin: "HubSpotty", industry: "CRM", icon: "🟠", accent: "#ff7a59", accent2: "#33475b", mode: "light", tagline: "CRM + marketing hub" },
  { no: 30, slug: "zendesk", name: "Zendesk", skin: "Zendeskly", industry: "Support SaaS", icon: "🎧", accent: "#03363d", accent2: "#17494d", mode: "light", tagline: "Support desk" },
  { no: 31, slug: "intercom", name: "Intercom", skin: "Intercomm", industry: "Support SaaS", icon: "💬", accent: "#1f8ded", accent2: "#0b1f33", mode: "light", tagline: "Customer messenger" },
  { no: 32, slug: "zoho-crm", name: "Zoho CRM", skin: "Zohoo CRM", industry: "CRM", icon: "🧩", accent: "#e42527", accent2: "#226db4", mode: "light", tagline: "Business CRM suite" },
  { no: 33, slug: "freshdesk", name: "Freshdesk", skin: "Freshdeskly", industry: "Support SaaS", icon: "🌿", accent: "#25c16f", accent2: "#12344d", mode: "light", tagline: "Helpdesk" },
  { no: 34, slug: "servicenow", name: "ServiceNow", skin: "ServiceNowly", industry: "ITSM", icon: "🛠️", accent: "#62d84e", accent2: "#032d42", mode: "light", tagline: "ITSM portal" },
  { no: 35, slug: "slack", name: "Slack", skin: "Slacky", industry: "Work collab", icon: "#️⃣", accent: "#4a154b", accent2: "#36c5f0", mode: "light", tagline: "Team messaging" },
  { no: 36, slug: "microsoft-teams", name: "Microsoft Teams", skin: "Teamz", industry: "Work collab", icon: "👥", accent: "#5b5fc7", accent2: "#242424", mode: "light", tagline: "Meetings and chat" },
  { no: 37, slug: "zoom", name: "Zoom", skin: "Zoomly", industry: "Work collab", icon: "🎥", accent: "#0b5cff", accent2: "#232333", mode: "light", tagline: "Video meetings" },
  { no: 38, slug: "notion", name: "Notion", skin: "Notionly", industry: "Work collab", icon: "📝", accent: "#191919", accent2: "#f5f5f5", mode: "light", tagline: "Docs and databases" },
  { no: 39, slug: "airtable", name: "Airtable", skin: "Airtably", industry: "Work collab", icon: "🗂️", accent: "#fcb400", accent2: "#18bfff", mode: "light", tagline: "Spreadsheet-database" },
  { no: 40, slug: "asana", name: "Asana", skin: "Asanah", industry: "Work collab", icon: "✅", accent: "#f06a6a", accent2: "#1e1f21", mode: "light", tagline: "Work management" },
  { no: 41, slug: "jira", name: "Jira", skin: "Jirah", industry: "Work collab", icon: "🐞", accent: "#0052cc", accent2: "#172b4d", mode: "light", tagline: "Issue tracking" },
  { no: 42, slug: "monday", name: "Monday.com", skin: "Mondayly", industry: "Work collab", icon: "🟣", accent: "#6161ff", accent2: "#ff3d57", mode: "light", tagline: "Work OS boards" },
  { no: 43, slug: "docusign", name: "DocuSign", skin: "DocuSigned", industry: "Docs productivity", icon: "✍️", accent: "#4c00ff", accent2: "#191823", mode: "light", tagline: "E-signature" },
  { no: 44, slug: "dropbox", name: "Dropbox", skin: "Dropboxy", industry: "Docs productivity", icon: "📁", accent: "#0061ff", accent2: "#1e1919", mode: "light", tagline: "Cloud file storage" },
  { no: 45, slug: "google-drive", name: "Google Drive", skin: "Drively", industry: "Docs productivity", icon: "🗃️", accent: "#1a73e8", accent2: "#34a853", mode: "light", tagline: "Docs and drive" },
  { no: 46, slug: "calendly", name: "Calendly", skin: "Calendlee", industry: "Docs productivity", icon: "📅", accent: "#006bff", accent2: "#0b3558", mode: "light", tagline: "Scheduling links" },
  { no: 47, slug: "netflix", name: "Netflix", skin: "Netflixy", industry: "Streaming", icon: "🎬", accent: "#e50914", accent2: "#141414", mode: "dark", tagline: "Streaming" },
  { no: 48, slug: "spotify", name: "Spotify", skin: "Spotifly", industry: "Streaming", icon: "🎵", accent: "#1db954", accent2: "#121212", mode: "dark", tagline: "Music streaming" },
  { no: 49, slug: "youtube", name: "YouTube", skin: "YouTubely", industry: "Streaming", icon: "▶️", accent: "#ff0000", accent2: "#0f0f0f", mode: "light", tagline: "Video platform" },
  { no: 50, slug: "disney-hotstar", name: "Disney+ Hotstar", skin: "Hotstarry", industry: "Streaming", icon: "⭐", accent: "#1f80e0", accent2: "#0f1014", mode: "dark", tagline: "Live sports and streaming" },
];

// use-case number -> [flow slug, pattern engine, ship day]
/** @type {Record<string,[string,Pattern,number]>} */
const FLOW_META = {
  "1.1": ["search-to-product", "crud", 13],
  "1.2": ["add-to-cart-variant", "checkout", 2],
  "1.3": ["one-click-checkout", "checkout", 3],
  "1.4": ["order-tracking", "tracker", 2],
  "1.5": ["return-initiation", "wizard", 13],
  "2.1": ["guest-checkout", "checkout", 3],
  "2.2": ["discount-code", "checkout", 3],
  "2.3": ["checkout-extension", "checkout", 3],
  "2.4": ["admin-order-creation", "crud", 14],
  "2.5": ["theme-update-smoke", "checkout", 14],
  "3.1": ["search-with-filters", "crud", 14],
  "3.2": ["cart-exchange-offer", "checkout", 3],
  "3.3": ["cod-checkout", "checkout", 3],
  "3.4": ["supercoins-balance", "custom", 14],
  "4.1": ["store-pickup", "checkout", 3],
  "4.2": ["grocery-substitution", "checkout", 3],
  "4.3": ["membership-upsell", "checkout", 3],
  "4.4": ["reorder-from-history", "crud", 3],
  "5.1": ["personalized-item", "checkout", 3],
  "5.2": ["shop-search-favorite", "crud", 14],
  "5.3": ["multi-seller-cart", "checkout", 3],
  "5.4": ["review-submission", "feed", 14],
  "6.1": ["bid-placement", "custom", 7],
  "6.2": ["buy-it-now", "checkout", 3],
  "6.3": ["best-offer", "wizard", 8],
  "6.4": ["seller-listing", "wizard", 10],
  "7.1": ["multi-store-cart", "checkout", 3],
  "7.2": ["replacement-preferences", "checkout", 11],
  "7.3": ["delivery-slot-checkout", "booking", 3],
  "7.4": ["tip-adjustment", "checkout", 3],
  "8.1": ["size-guide", "checkout", 7],
  "8.2": ["member-exclusive", "auth", 7],
  "8.3": ["snkrs-draw", "custom", 12],
  "8.4": ["checkout-saved-card", "checkout", 3],
  "9.1": ["hosted-checkout", "checkout", 4],
  "9.2": ["3ds-challenge", "checkout", 4],
  "9.3": ["declined-card-recovery", "checkout", 4],
  "9.4": ["billing-portal", "crud", 14],
  "9.5": ["dashboard-payment-lookup", "crud", 14],
  "10.1": ["express-checkout", "checkout", 4],
  "10.2": ["guest-card-payment", "checkout", 4],
  "10.3": ["send-money", "wizard", 14],
  "10.4": ["dispute-filing", "wizard", 14],
  "10.5": ["currency-conversion", "wizard", 14],
  "11.1": ["checkout-modal", "checkout", 4],
  "11.2": ["upi-intent", "checkout", 4],
  "11.3": ["emi-options", "checkout", 4],
  "11.4": ["payment-link", "checkout", 4],
  "12.1": ["checkout-link", "checkout", 4],
  "12.2": ["invoice-pay", "checkout", 4],
  "12.3": ["tip-and-receipt", "checkout", 4],
  "12.4": ["refund-dashboard", "crud", 14],
  "13.1": ["drop-in-payment", "checkout", 4],
  "13.2": ["ideal-redirect", "checkout", 4],
  "13.3": ["stored-card-reuse", "checkout", 4],
  "13.4": ["webhook-status-parity", "tracker", 14],
  "14.1": ["pay-in-4", "checkout", 4],
  "14.2": ["credit-decline-fallback", "checkout", 4],
  "14.3": ["payment-schedule", "tracker", 6],
  "14.4": ["return-adjusts-installments", "tracker", 7],
  "15.1": ["transfer-quote", "wizard", 5],
  "15.2": ["add-recipient", "wizard", 5],
  "15.3": ["transfer-tracking", "tracker", 5],
  "15.4": ["balance-conversion", "custom", 5],
  "16.1": ["market-buy", "custom", 7],
  "16.2": ["limit-order", "custom", 7],
  "16.3": ["portfolio-value", "crud", 7],
  "16.4": ["instant-deposit", "wizard", 7],
  "16.5": ["options-chain", "crud", 7],
  "17.1": ["intraday-order", "custom", 7],
  "17.2": ["gtt-trigger", "custom", 7],
  "17.3": ["holdings-pnl", "crud", 7],
  "17.4": ["funds-upi", "wizard", 7],
  "18.1": ["crypto-buy", "checkout", 7],
  "18.2": ["recurring-buy", "wizard", 7],
  "18.3": ["send-to-address", "wizard", 7],
  "18.4": ["price-alert", "crud", 7],
  "19.1": ["card-freeze", "custom", 5],
  "19.2": ["currency-exchange", "custom", 6],
  "19.3": ["split-bill", "wizard", 6],
  "19.4": ["savings-vault", "custom", 6],
  "20.1": ["upi-transfer", "wizard", 6],
  "20.2": ["mobile-recharge", "checkout", 6],
  "20.3": ["electricity-bill", "checkout", 6],
  "20.4": ["wallet-to-bank", "wizard", 6],
  "20.5": ["movie-ticket", "booking", 6],
  "21.1": ["qr-scan-pay", "wizard", 6],
  "21.2": ["autopay-mandate", "wizard", 6],
  "21.3": ["history-filter", "crud", 6],
  "21.4": ["bike-insurance-quote", "wizard", 6],
  "22.1": ["pay-with-note", "feed", 6],
  "22.2": ["request-and-remind", "feed", 6],
  "22.3": ["cash-out", "wizard", 6],
  "22.4": ["card-transaction-feed", "feed", 6],
  "23.1": ["login-2fa", "auth", 2],
  "23.2": ["zelle-transfer", "wizard", 5],
  "23.3": ["bill-pay-scheduling", "wizard", 5],
  "23.4": ["statement-download", "custom", 5],
  "23.5": ["card-dispute", "wizard", 5],
  "24.1": ["netbanking-login", "auth", 5],
  "24.2": ["imps-transfer", "wizard", 5],
  "24.3": ["fd-creation", "wizard", 5],
  "24.4": ["card-statement", "crud", 5],
  "25.1": ["rewards-redemption", "wizard", 5],
  "25.2": ["payment-scheduling", "wizard", 5],
  "25.3": ["dispute-charge", "wizard", 5],
  "25.4": ["offers-enrollment", "crud", 5],
  "26.1": ["instant-quote", "wizard", 2],
  "26.2": ["policy-purchase", "checkout", 8],
  "26.3": ["claim-filing", "wizard", 8],
  "26.4": ["coverage-adjustment", "wizard", 8],
  "27.1": ["term-comparison", "crud", 8],
  "27.2": ["lead-callback", "wizard", 8],
  "27.3": ["health-plan-filter", "crud", 8],
  "27.4": ["premium-calculator", "custom", 8],
  "28.1": ["lead-creation", "crud", 8],
  "28.2": ["opportunity-kanban", "crud", 8],
  "28.3": ["report-filter", "crud", 8],
  "28.4": ["record-edit-overlay", "crud", 8],
  "28.5": ["screen-flow", "wizard", 8],
  "29.1": ["form-to-contact", "crud", 8],
  "29.2": ["deal-pipeline-drag", "crud", 8],
  "29.3": ["sequence-enrollment", "crud", 8],
  "29.4": ["meeting-link-booking", "booking", 8],
  "30.1": ["widget-ticket", "wizard", 9],
  "30.2": ["agent-reply-status", "crud", 9],
  "30.3": ["macro-application", "crud", 9],
  "30.4": ["help-center-search", "crud", 9],
  "30.5": ["sla-breach-indicator", "tracker", 9],
  "31.1": ["messenger-conversation", "feed", 9],
  "31.2": ["bot-handoff", "feed", 9],
  "31.3": ["article-suggestion", "feed", 9],
  "31.4": ["outbound-message", "custom", 9],
  "32.1": ["lead-import-mapping", "wizard", 9],
  "32.2": ["workflow-rule", "crud", 9],
  "32.3": ["blueprint-transition", "wizard", 9],
  "32.4": ["dashboard-kpi", "crud", 9],
  "33.1": ["email-to-ticket", "custom", 9],
  "33.2": ["canned-response", "crud", 9],
  "33.3": ["ticket-merge", "crud", 9],
  "33.4": ["portal-ticket-view", "auth", 9],
  "34.1": ["incident-creation", "crud", 10],
  "34.2": ["approval-workflow", "wizard", 10],
  "34.3": ["catalog-order", "wizard", 10],
  "34.4": ["knowledge-search", "crud", 10],
  "35.1": ["thread-reply", "feed", 2],
  "35.2": ["file-upload-preview", "feed", 10],
  "35.3": ["search-channels", "crud", 10],
  "35.4": ["huddle-start", "media", 10],
  "35.5": ["workflow-form", "wizard", 10],
  "36.1": ["meeting-join", "media", 10],
  "36.2": ["mention-notification", "feed", 10],
  "36.3": ["file-coauthor", "custom", 10],
  "36.4": ["tab-app-load", "custom", 10],
  "37.1": ["meeting-registration", "booking", 10],
  "37.2": ["waiting-room", "media", 10],
  "37.3": ["screen-share", "media", 10],
  "37.4": ["cloud-recording", "media", 10],
  "38.1": ["page-blocks", "custom", 11],
  "38.2": ["database-filter-sort", "crud", 11],
  "38.3": ["share-to-web", "custom", 11],
  "38.4": ["template-duplication", "crud", 11],
  "38.5": ["comment-mention", "feed", 11],
  "39.1": ["grid-crud", "crud", 2],
  "39.2": ["form-view-submission", "wizard", 11],
  "39.3": ["kanban-drag", "crud", 11],
  "39.4": ["automation-run", "crud", 11],
  "40.1": ["task-creation", "crud", 11],
  "40.2": ["board-move", "crud", 11],
  "40.3": ["subtask-dependency", "crud", 11],
  "40.4": ["my-tasks-sort", "crud", 11],
  "41.1": ["issue-creation", "crud", 11],
  "41.2": ["sprint-board-drag", "crud", 11],
  "41.3": ["jql-filter", "crud", 11],
  "41.4": ["transition-validation", "crud", 11],
  "42.1": ["board-item", "crud", 12],
  "42.2": ["automation-recipe", "crud", 12],
  "42.3": ["dashboard-widget", "crud", 12],
  "42.4": ["guest-board-sharing", "auth", 12],
  "43.1": ["envelope-send", "wizard", 12],
  "43.2": ["signing-ceremony", "wizard", 12],
  "43.3": ["template-reuse", "wizard", 12],
  "43.4": ["decline-void", "tracker", 12],
  "44.1": ["upload-share-link", "crud", 12],
  "44.2": ["folder-permission", "crud", 12],
  "44.3": ["file-request", "wizard", 12],
  "44.4": ["version-history", "crud", 12],
  "45.1": ["share-permission-levels", "crud", 12],
  "45.2": ["realtime-coedit", "custom", 12],
  "45.3": ["drive-search", "crud", 12],
  "45.4": ["offline-sync", "custom", 12],
  "46.1": ["invitee-booking", "booking", 2],
  "46.2": ["availability-rules", "booking", 13],
  "46.3": ["reschedule", "booking", 13],
  "46.4": ["paid-booking", "booking", 13],
  "47.1": ["signup-plan", "checkout", 13],
  "47.2": ["playback-resume", "media", 2],
  "47.3": ["profile-pin", "auth", 13],
  "47.4": ["offline-download", "media", 13],
  "47.5": ["cancel-rejoin", "wizard", 13],
  "48.1": ["premium-upgrade", "checkout", 13],
  "48.2": ["playlist-create", "media", 13],
  "48.3": ["cross-device-continue", "media", 13],
  "48.4": ["family-invite", "wizard", 13],
  "49.1": ["video-upload", "wizard", 13],
  "49.2": ["comment-pin", "feed", 13],
  "49.3": ["background-play-entitlement", "auth", 13],
  "49.4": ["channel-membership", "checkout", 13],
  "50.1": ["live-sports-playback", "media", 13],
};

// Real brand names -> thin fictional skin names, applied to objectives/assertions.
const BRAND_MAP = [
  ["Walmart+", "Walmartly+"], ["Amazon", "Amazonia"], ["Shopify", "Shopifly"], ["Flipkart", "Flipmart"],
  ["SuperCoins", "SuperCoins"], ["Walmart", "Walmartly"], ["Etsy", "Etsily"], ["eBay", "eBidz"],
  ["Instacart", "Instakart"], ["SNKRS", "SNKRZ"], ["Nike", "Nyke"], ["Stripe Checkout", "Stripely Checkout"],
  ["Stripe", "Stripely"], ["PayPal", "PayPally"], ["Razorpay", "Razorpaid"], ["Square", "Squarely"],
  ["Adyen", "Adyenly"], ["Klarna app", "Klarnah app"], ["Klarna", "Klarnah"], ["Wise", "Wyse"],
  ["Robinhood", "Robinhoot"], ["Kite", "Kyte"], ["Zerodha", "Zerodhi"], ["Coinbase", "Coinbayse"],
  ["Revolut", "Revolute"], ["Paytm", "Paytum"], ["PhonePe", "PhonePay"], ["Venmo", "Venmoo"],
  ["Zelle", "Zelly"], ["Chase", "Chaise"], ["HDFC", "HDFB"], ["American Express", "Amerix"],
  ["Membership Rewards", "Membership Rewards"], ["Lemonade", "Lemonaid"], ["Policybazaar", "PolicyMart"],
  ["Salesforce", "Salesforze"], ["Lightning", "Lightning"], ["LWC", "LWC"], ["HubSpot", "HubSpotty"],
  ["Zendesk", "Zendeskly"], ["Intercom", "Intercomm"], ["Zoho", "Zohoo"], ["Freshdesk", "Freshdeskly"],
  ["ServiceNow", "ServiceNowly"], ["RITM", "RITM"], ["Slack", "Slacky"], ["Teams", "Teamz"],
  ["Zoom", "Zoomly"], ["Notion", "Notionly"], ["Airtable", "Airtably"], ["Asana", "Asanah"],
  ["Jira", "Jirah"], ["JQL", "JQL"], ["Monday", "Mondayly"], ["DocuSign", "DocuSigned"],
  ["Dropbox", "Dropboxy"], ["Google Drive", "Drively"], ["Calendly", "Calendlee"], ["Netflix", "Netflixy"], ["Disney+ Hotstar", "Hotstarry"], ["Hotstar", "Hotstarry"],
  ["Spotify", "Spotifly"], ["YouTube", "YouTubely"],
];
const BRAND_RE = new RegExp(
  BRAND_MAP.map(([a]) => a.replace(/[+.]/g, "\\$&")).sort((x, y) => y.length - x.length).join("|"),
  "g"
);
const BRAND_LOOKUP = Object.fromEntries(BRAND_MAP);
/** Single-pass brand -> skin substitution (longest match first, no re-matching). */
export function skinText(s) {
  return String(s).replace(BRAND_RE, (m) => BRAND_LOOKUP[m] ?? m);
}

const MOBILE_UC = new Set(["2.5", "20.1", "20.2", "20.3", "20.4", "20.5", "21.1", "21.2", "21.3", "21.4", "22.1", "22.2", "22.3", "22.4", "19.1", "19.2", "19.3", "19.4", "47.4", "48.3", "49.3"]);

/** @type {Flow[]} */
export const FLOWS = CATALOG.map((row) => {
  const ent = ENTITIES.find((e) => e.no === row.entityNo);
  const [slug, pattern, day] = FLOW_META[row.uc];
  const path = `/${ent.slug}/${slug}`;
  return {
    ...row,
    entitySlug: ent.slug,
    skin: ent.skin,
    slug,
    pattern,
    day,
    path,
    url: SITE_URL + path,
    testPath: `tests/${ent.slug}/${slug}_test.md`,
    skinObjective: skinText(row.objective),
    skinAssertion: skinText(row.assertion),
    mobile: MOBILE_UC.has(row.uc),
  };
});

export const INDUSTRIES = [...new Set(ENTITIES.map((e) => e.industry))];

export function getEntity(slug) {
  return ENTITIES.find((e) => e.slug === slug) || null;
}
export function getFlowsForEntity(slug) {
  return FLOWS.filter((f) => f.entitySlug === slug);
}
export function getFlow(entitySlug, flowSlug) {
  return FLOWS.find((f) => f.entitySlug === entitySlug && f.slug === flowSlug) || null;
}
export function flowKey(f) {
  return `${f.entitySlug}/${f.slug}`;
}
