// Generates one Kane CLI test per catalog flow (tests/{entity}/{flow}_test.md)
// plus tests/INDEX.md. Existing test files are never overwritten (they get
// hand-refined once the flow is built); only missing drafts are created.
// Usage: node scripts/gen-tests.mjs [--force <entity/flow>]
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { FLOWS, ENTITIES, SITE_URL, PATTERN_LABELS } from "../lib/registry.js";
import { hasFlow } from "../lib/flow-loaders.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const TESTS = path.join(ROOT, "tests");
const STATUS_FILE = path.join(TESTS, "status.json");
const status = fs.existsSync(STATUS_FILE) ? JSON.parse(fs.readFileSync(STATUS_FILE, "utf8")) : {};
const force = new Set(process.argv.includes("--force") ? [process.argv[process.argv.indexOf("--force") + 1]] : []);

function draft(f) {
  const tags = [f.entitySlug, f.industry.toLowerCase().replace(/\s+/g, "-"), f.pattern];
  return `---
mode: testing
url: ${f.url}?reset=true
max_steps: 30
tags: [${tags.join(", ")}]
variables:
  demo_email: { value: "demo@evals.dev" }
  demo_password: { value: "Demo123!", secret: true }
  otp: { value: "123456" }
  card_success: { value: "4242 4242 4242 4242" }
  card_decline: { value: "4000 0000 0000 0002" }
---

# ${f.skin} ${f.uc}: ${f.useCase}

<!-- DRAFT generated from the catalog. Refined with concrete steps once the flow ships (day ${f.day}). -->
<!-- Catalog entity: ${f.entity} · Industry: ${f.industry} · Pattern: ${PATTERN_LABELS[f.pattern]} -->

## Open the flow
Go to ${f.url}?reset=true and verify the text "Use case ${f.uc}" and "${f.useCase}" are visible at the top of the page.

## Objective
${f.skinObjective}.

## Key assertion
Verify: ${f.skinAssertion}.
`;
}

let created = 0;
for (const f of FLOWS) {
  const file = path.join(ROOT, f.testPath);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  if (!fs.existsSync(file) || force.has(`${f.entitySlug}/${f.slug}`)) {
    fs.writeFileSync(file, draft(f));
    created++;
  }
}

// INDEX.md
const lines = [];
lines.push("# Entity Evals · Kane CLI test index");
lines.push("");
lines.push(`Generated by \`node scripts/gen-tests.mjs\` from \`lib/registry.js\`. ${FLOWS.length} tests, one per catalog use case (rows 2-210, Owner = Bhawana).`);
lines.push("");
lines.push("Run one: `kane-cli testmd run tests/amazon/add-to-cart-variant_test.md --agent --headless`");
lines.push("");
lines.push("Status legend · **Flow**: `live` (deployed) or `day N` (scheduled). **Test**: `verified` (executed against the live URL and passed), `draft` (generated from the catalog, not yet executed).");
lines.push("");
const live = FLOWS.filter((f) => hasFlow(`${f.entitySlug}/${f.slug}`)).length;
const verified = FLOWS.filter((f) => status[`${f.entitySlug}/${f.slug}`] === "verified").length;
lines.push(`| Total flows | Live | Tests verified |`);
lines.push(`|---|---|---|`);
lines.push(`| ${FLOWS.length} | ${live} | ${verified} |`);
lines.push("");
for (const e of ENTITIES) {
  const flows = FLOWS.filter((f) => f.entitySlug === e.slug);
  lines.push(`## ${e.no}. ${e.skin} (${e.name}) · ${e.industry}`);
  lines.push("");
  lines.push("| UC | Use case | URL | test.md | Flow | Test |");
  lines.push("|---|---|---|---|---|---|");
  for (const f of flows) {
    const key = `${f.entitySlug}/${f.slug}`;
    const fl = hasFlow(key) ? "live" : `day ${f.day}`;
    const ts = status[key] || "draft";
    lines.push(`| ${f.uc} | ${f.useCase} | [${f.path}](${f.url}) | [${f.testPath}](../${f.testPath}) | ${fl} | ${ts} |`);
  }
  lines.push("");
}
fs.writeFileSync(path.join(TESTS, "INDEX.md"), lines.join("\n"));
console.log(`tests: ${created} created, ${FLOWS.length} total · live flows ${live} · verified ${verified} · INDEX.md written`);
